-- Write your SQL statements below
use collegeDBBCA;
CREATE TABLE DEPARTMENT (DEPARTMENT_ID INT PRIMARY KEY,DEPARTMENT_NAME VARCHAR(100),HOD VARCHAR(100));
SELECT*FROM DEPARTMENT;
use collegeDB;
CREATE TABLE STUDENT(STUDENTID int (5)PRIMARY KEY,STUDENTNAME VARCHAR(20),DOB DATE NOT NULL,GENDER VARCHAR (10) NOT NULL,DEPARTMENTID int(5)NOT NULL,CONSTRAINT UQ_STUDENTNAME UNIQUE (STUDENTNAME));
